title: 京都府北部エリア
description: 京都府北部エリアでテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1XVJBkBmV8EKeshvrMfADwBrtc9brFi4aUuBUBywQxdo/export?format=csv&gid=0
repository: https://github.com/masaki0418/app/
form_url: https://docs.google.com/forms/d/e/1FAIpQLSd7LJZ5Mz148OmJk-JC4khn_b3cgyOwpunNEr2XRlpcfp4Umw/viewform
