title: 京都府舞鶴市
description: 京都府舞鶴市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1Dke_0z3KkPqUvZHxbgqETYIdukcG-J0WtNjr7S7CLIg/export?format=csv&gid=1264520528
repository: https://github.com/masaki0418/app/
form_url: https://docs.google.com/forms/d/e/1FAIpQLSd7LJZ5Mz148OmJk-JC4khn_b3cgyOwpunNEr2XRlpcfp4Umw/viewform
